services:
  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
  encore:
    restart: unless-stopped
    build: docker/encore
    volumes:
      - ./:/usr/src/app
