# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    container.dumper.inline_factories: true
    app.cdn.path: "https://fra1.digitaloceanspaces.com/netkare"
    app.image.library: "gd"
    assets_directory: "%kernel.project_dir%/assets"
    uploads_directory: "%kernel.project_dir%/public/uploads"
    announcements_directory: "%uploads_directory%/announcements"
    archives_directory: "%uploads_directory%/archives"
    classrooms_directory: "%uploads_directory%/classrooms"
    excels_directory: "%uploads_directory%/excels"
    passwords_directory: "%uploads_directory%/passwords"
    products_directory: "%uploads_directory%/products"
    schools_directory: "%uploads_directory%/schools"
    node_modules_directory: "%kernel.project_dir%/node_modules"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            - "../src/Tests/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\DownloadMaker\YearbookDownloadMaker:
        arguments:
            $assetsDirectory: "%assets_directory%"
            $schoolsDirectory: "%schools_directory%"
            $nodeModulesDirectory: "%node_modules_directory%"

    App\Service\ImageResizer:
        arguments:
            $library: "%app.image.library%"

    App\Service\ObjectStorage:
        arguments:
            $args:
                version: "latest"
                region: "us-east-1"
                endpoint: "https://fra1.digitaloceanspaces.com"
                credentials:
                    key: "2AYAWJ34JFYUOFSXYZ6M"
                    secret: "uGFUAta1WjWvl9HIupVYHzMMmCtLAatqnlNMq54re50"
            $bucket: "netkare"

    App\Service\Pagination:

    App\Service\Search:

    App\Service\PhotoLayout\Biometric2:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\PhotoLayout\Biometric4:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\PhotoLayout\HeadShot2:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\PhotoLayout\HeadShot4:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\PhotoLayout\HeadShot8:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\StudentLayout\ExecutiveAlbum30:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\StudentLayout\ExecutiveAlbum42:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\StudentLayout\ExecutiveAlbum56:
        arguments:
            $projectDirectory: "%kernel.project_dir%"

    App\Service\StudentLayout\Transcript:
        arguments:
            $projectDirectory: "%kernel.project_dir%"
